name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compile:
    name: Compile Example PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: typst-community/setup-typst@v4
      - name: Compile example PDF
        run: typst compile main.typ
      - name: Upload as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: main.pdf
  deploy_pages:
    name: Deploy to Pages
    needs:
      - compile
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
